name: Scandocs

include:
  - xcodegen-scripts/base.yml
  - path: xcodegen-scripts/base.yml
    relativePaths: false

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID)
    BUILD_NUMBER: $(BUILD_NUMBER)
    VERSION_NAME: $(VERSION_NAME)
    PROVISIONING_PROFILE_SPECIFIER: $(APP_PROVISIONING_PROFILE)
    CODE_SIGN_IDENTITY: $(CODE_SIGN_IDENTITY)

targets:
  Scandocs:
    type: application
    platform: iOS
    sources:
      - path: Scandocs
        name: Scandocs
      - Modules/SDCameraScan/SDCameraScan/Resource/SDCameraScanAssets.xcassets
    settings:
      base:
        PRODUCT_NAME: $(APP_NAME)
        TARGETED_DEVICE_FAMILY: $(TARGETED_DEVICE_FAMILY)
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(SWIFT_ACTIVE_COMPILATION_CONDITIONS)
        CODE_SIGN_ENTITLEMENTS: "Scandocs/Supporting Files/Scandocs.entitlements"
    postBuildScripts:
      - name: Upload dSYMs Scripts
        path: xcodegen-scripts/upload_dsyms.sh
        basedOnDependencyAnalysis: YES
        showEnvVars: YES
        inputFiles:
        - "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"
        - "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${PRODUCT_NAME}"
        - "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Info.plist"
        - "$(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/GoogleService-Info.plist"
        - "$(TARGET_BUILD_DIR)/$(EXECUTABLE_PATH)"

schemes:
  Scandocs:
    build:
      targets:
        Scandocs: all
    run:
      config: Development
    # test:
    #   config: Development
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release