# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Preparing Certificate and Provisioning Profiles on New Device Setup"
  lane :prepare do
    match(
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      app_identifier: "com.scandocs.ios",
      type: "development",
      readonly: true
    )

    match(
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      app_identifier: "com.scandocs.ios",
      type: "adhoc",
      readonly: true
    )

    match(
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      app_identifier: "com.scandocs.ios",
      type: "appstore",
      readonly: true
    )
  end
end
