platform :ios, '15.0'

target 'SDCameraScan' do
  use_frameworks!
  pod 'SDCoreKit', :path => '../SDCoreKit'
  pod 'SDScanKit', :path => '../SDScanKit'

  target 'ExampleApps' do
    inherit! :complete
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end