# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build TestFlight

on:
  workflow_dispatch:

jobs:
  prepare_provisioning_profiles:
    name: Build TestFlight
    runs-on: macos-latest
    
    steps:
      - name: Xcode Select Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1'

      - name: Checkout Branch
        uses: actions/checkout@v2
      
      - name: Install Bundle Dependency
        run: |
          bundle install

      - name: Install XcodeGen
        run: |
          brew install xcodegen

      - name: Build IPA and Upload to TestFlight using Fastlane
        env:
          APP_STORE_CONNECT_API_KEY_IN_HOUSE: ${{ vars.APP_STORE_CONNECT_API_KEY_IN_HOUSE }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ vars.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: ${{ vars.APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64 }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ vars.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ vars.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ vars.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_KEYCHAIN: ${{ vars.MATCH_KEYCHAIN }}
          MATCH_PASSWORD: ${{ vars.MATCH_PASSWORD }}
          DISCORD_WEBHOOK_URL: ${{ vars.DISCORD_WEBHOOK_URL }}
          BUILD_NUMBER: ${{ github.run_number }}
          WORKFLOW_NAME: ${{ github.workflow }}
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          bundle exec fastlane build_testflight