# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Prepare Provisioning Profiles

on:
  workflow_dispatch:

jobs:
  prepare_provisioning_profiles:
    name: Prepare Provisioning Profiles
    runs-on: macos-latest
    
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Install Bundle Dependency
        run: |
          bundle install
      
      - name: Run Match
        run: |
          bundle exec fastlane prepare
      